apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: blocky
  namespace: default
spec:
  chart: blocky
  repo: https://k8s-at-home.com/charts/
  valuesContent: |-
    service:
      dns-udp:
        enabled: true
      dns-tcp:
        enabled: true
