apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: blocky-dns-udp
  namespace: default
spec:
  entryPoints:
    - dns-udp
  routes:
  - match: Host(`*`)
    kind: Rule
    services:
    - name: blocky-dns-udp
      port: 53