apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blocky-dns-tcp
  namespace: default
spec:
  entryPoints:
    - dns-tcp
  routes:
  - match: Host(`*`)
    kind: Rule
    services:
    - name: blocky-dns-tcp
      port: 53